### ISSUE TITLE
Certificati con scadenza molto breve

### ISSUE THREAD

**Issue by bmonticini** [daserzw/satosa-oidc-to-saml#1]
La scadenza dei certificati nei metadata è veramente breve.
consiglio l'opzione -days 3650

openssl req -x509 -nodes -days <# of days> -newkey rsa:<keysize> -keyout /config/ssl/ssl.key/<key_name>.key -out /config/ssl/ssl.crt/<cert_name>.crt

**Comment by daserzw** [comment]
Thanks, fixed.
